DROP TABLE IF EXISTS locations CASCADE;
CREATE TABLE locations (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  Description VARCHAR(255),
  title VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(255) NOT NULL,
  image VARCHAR(255) NOT NULL
);
